Update patch set 1
Patch Set 1:

that sounds fine, Oskar.

This one fixes compilation with CONFIG_PID_NS enabled. Without this, kernel will fail during final linking with;

undefined reference to `pidns_operations'

The namespace stuff probably isn't needing to be enabled for cm-13, but regardless this is the upstream fix from linux-stable.

The namespace_fixes are required for seccomp-bpf on klte, which I will be submitting for cm-14 klte. However, I do use seccomp-bpf with cm-13 too for chrome/chromium sandboxing. So I could submit it for both cm13/14, if you are interested.

Patch-set: 1